version: '3'
services:
  banner_data_initializer:
    container_name: 'banner_data_initializer'
    build: banner_data_initializer/.
    volumes:
      - ./data:/data
      - ./banner_data_initializer/banner_data_processor.py:/app/banner_data_processor.py
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64  # added so it works on Apple M1 - you can remove this otherwise.
    container_name: "mysql"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "banner"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  banner_web_app:
    container_name: "banner_web_app"
    build: banner_web_app/.
    volumes:
      - ./banner_web_app/.:/app
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:alpine
    expose:
      - "6379"

volumes:
  my-db: